# Generated by Django 3.2 on 2022-01-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='fb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='insta',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='tw',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='yt',
            field=models.URLField(blank=True, null=True),
        ),
    ]
