# Generated by Django 3.2 on 2022-01-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220107_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'verbose_name_plural': '3. Banner Image'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '7. Customer'},
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
