# Generated by Django 3.2 on 2022-01-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_customer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='product',
        ),
    ]
