# Generated by Django 3.2 on 2022-01-11 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0019_customer_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='OrderItem',
        ),
    ]
