# Generated by Django 3.2 on 2022-01-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_customer_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': '7. OrderItem'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
